#!/bin/bash
# regenerate apitest_have.h: which vendor IMP_/SU_ functions the ingenic-headers of each SoC declare
HDR=${HDR:-/mnt/NVMe/git/thingino-ciao-openstack/dl/thingino-raptor-hal/git/ingenic-headers}
D=$(cd "$(dirname "$0")" && pwd)
{
echo "/* generated by gen_have.sh - vendor functions declared in the ingenic-headers of each SoC */"
first=1
for e in T10:T10/3.12.0/zh T20:T20/3.12.0/zh T21:T21/1.0.33/zh T23:T23/1.3.0/zh T30:T30/1.0.5/zh T31:T31/1.1.6/en T41:T41/1.2.6/zh; do
  soc=${e%%:*}; inc=$HDR/${e#*:}
  [ $first = 1 ] && echo "#if defined(PLATFORM_$soc)" || echo "#elif defined(PLATFORM_$soc)"
  first=0
  tmp=$(mktemp --suffix=.c)
  for h in $inc/imp/imp_*.h $inc/sysutils/su_*.h; do echo "#include \"$h\""; done > $tmp
  gcc -E -P -I$inc -I$inc/imp $tmp 2>/dev/null | grep -oE "\b(IMP|SU)_[A-Za-z0-9_]+[[:space:]]*\(" | tr -d '( \t' | sort -u | sed 's/^/#define HAS_/;s/$/ 1/'
  rm -f $tmp
done
echo "#endif"
} > "$D/apitest_have.h"
# every declared function weak: an unexported one is NULL at run time (N/A line)
{
echo "/* generated by gen_have.sh - include AFTER the vendor headers */"
first=1
for e in T10 T20 T21 T23 T30 T31 T41; do
  [ $first = 1 ] && echo "#if defined(PLATFORM_$e)" || echo "#elif defined(PLATFORM_$e)"
  first=0
  awk -v soc="PLATFORM_$e" '$0 ~ "defined\\(" soc "\\)" {on=1; next} /^#elif|^#endif/ {on=0} on && /define HAS_/ {print "#pragma weak " substr($2,5)}' "$D/apitest_have.h"
done
echo "#endif"
} > "$D/apitest_weak.h"
grep -c define "$D/apitest_have.h"; grep -c pragma "$D/apitest_weak.h"
